import type { AssetClass } from "../domain/instruments.ts";
import { db } from "./index.ts";
import { instruments } from "./schema/instruments.ts";

interface Instrument {
  symbol: string;
  name: string;
  assetClass: AssetClass;
  pointValue: string;
  tickSize: string;
  profitCurrency: string;
}

const FUTURES: Instrument[] = [
  {
    symbol: "ES",
    name: "E-mini S&P 500",
    pointValue: "50",
    tickSize: "0.25",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "NQ",
    name: "E-mini Nasdaq-100",
    pointValue: "20",
    tickSize: "0.25",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "YM",
    name: "E-mini Dow",
    pointValue: "5",
    tickSize: "1",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "RTY",
    name: "E-mini Russell 2000",
    pointValue: "50",
    tickSize: "0.10",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "GC",
    name: "Gold",
    pointValue: "100",
    tickSize: "0.10",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "CL",
    name: "Crude Oil",
    pointValue: "1000",
    tickSize: "0.01",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "MES",
    name: "Micro E-mini S&P 500",
    pointValue: "5",
    tickSize: "0.25",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "MNQ",
    name: "Micro E-mini Nasdaq-100",
    pointValue: "2",
    tickSize: "0.25",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "MYM",
    name: "Micro E-mini Dow",
    pointValue: "0.50",
    tickSize: "1",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "M2K",
    name: "Micro E-mini Russell 2000",
    pointValue: "5",
    tickSize: "0.10",
    assetClass: "future",
    profitCurrency: "USD",
  },
  {
    symbol: "MGC",
    name: "Micro Gold",
    pointValue: "10",
    tickSize: "0.10",
    assetClass: "future",
    profitCurrency: "USD",
  },
];

// Every FTMO CFD except equities (decided 2026-09-26, ftmo-cfd-instruments),
// from https://ftmo.com/wp-json/ftmo/symbols — the data behind
// ftmo.com/en/symbols — as of 2026-09-26. Curated by hand from that snapshot,
// never fetched at runtime.
//
// - `symbol` as MetaTrader writes it in the export: `EURUSD`, not `EUR/USD`.
//   A CFD is its own instrument — `US100.cash` is not `NQ`.
// - `pointValue` is FTMO's contract size: points × lots × point value is the
//   P&L, checked against the sample file (ftmo-import).
// - `tickSize` is one unit of the last of FTMO's `digits`.
// - `profitCurrency` is the currency that P&L is in; everything but USD is
//   converted with the ECB rate of the trade date.
// - USD/CNH is left out: the ECB publishes no CNH rate to convert it with.
const CFDS: Instrument[] = [
  {
    symbol: "AUS200.cash",
    name: "Australia 200 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "AUD",
  },
  {
    symbol: "US30.cash",
    name: "Dow Jones Industrial Average Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "SPN35.cash",
    name: "Spain 35 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "EUR",
  },
  {
    symbol: "EU50.cash",
    name: "Euro Stoxx 50 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "EUR",
  },
  {
    symbol: "FRA40.cash",
    name: "France 40 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "EUR",
  },
  {
    symbol: "GER40.cash",
    name: "German 40 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "EUR",
  },
  {
    symbol: "HK50.cash",
    name: "Hong Kong Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "HKD",
  },
  {
    symbol: "JP225.cash",
    name: "Japan 225 Index, Spot CFD",
    assetClass: "index",
    pointValue: "10",
    tickSize: "0.01",
    profitCurrency: "JPY",
  },
  {
    symbol: "N25.cash",
    name: "Netherlands 25 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "EUR",
  },
  {
    symbol: "US100.cash",
    name: "NASDAQ 100 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "US500.cash",
    name: "S&P 500 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "UK100.cash",
    name: "FTSE 100 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "GBP",
  },
  {
    symbol: "DXY.cash",
    name: "Dollar Index, Spot CFD",
    assetClass: "index",
    pointValue: "100",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "US2000.cash",
    name: "Russell 2000 Index, Spot CFD",
    assetClass: "index",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "AUDCAD",
    name: "Australian Dollar vs Canadian Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CAD",
  },
  {
    symbol: "AUDJPY",
    name: "Australian Dollar vs Japanese Yen",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "JPY",
  },
  {
    symbol: "AUDNZD",
    name: "Australian Dollar vs New Zealand Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "NZD",
  },
  {
    symbol: "AUDCHF",
    name: "Australian Dollar vs Swiss Franc",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CHF",
  },
  {
    symbol: "AUDUSD",
    name: "Australian Dollar vs US Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "GBPAUD",
    name: "Great Britain Pound vs Australian Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "AUD",
  },
  {
    symbol: "GBPCAD",
    name: "Great Britain Pound vs Canadian Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CAD",
  },
  {
    symbol: "GBPJPY",
    name: "Great Britain Pound vs Japanese Yen",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "JPY",
  },
  {
    symbol: "GBPNZD",
    name: "Great Britain Pound vs New Zealand Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "NZD",
  },
  {
    symbol: "GBPCHF",
    name: "Great Britain Pound vs Swiss Franc",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CHF",
  },
  {
    symbol: "GBPUSD",
    name: "Great Britain Pound vs US Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "CADJPY",
    name: "Canadian Dollar vs Japanese Yen",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "JPY",
  },
  {
    symbol: "CADCHF",
    name: "Canadian Dollar vs Swiss Franc",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CHF",
  },
  {
    symbol: "EURAUD",
    name: "Euro vs Australian Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "AUD",
  },
  {
    symbol: "EURGBP",
    name: "Euro vs Great Britain Pound",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "GBP",
  },
  {
    symbol: "EURCAD",
    name: "Euro vs Canadian Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CAD",
  },
  {
    symbol: "EURJPY",
    name: "Euro vs Japanese Yen",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "JPY",
  },
  {
    symbol: "EURCHF",
    name: "Euro vs Swiss Franc",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CHF",
  },
  {
    symbol: "EURUSD",
    name: "Euro vs United States Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "EURNZD",
    name: "Euro vs New Zealand Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "NZD",
  },
  {
    symbol: "NZDCAD",
    name: "New Zealand Dollar vs Canadian Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CAD",
  },
  {
    symbol: "NZDCHF",
    name: "New Zealand Dollar vs Swiss Franc",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CHF",
  },
  {
    symbol: "NZDJPY",
    name: "New Zealand Dollar vs Japanese Yen",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "JPY",
  },
  {
    symbol: "NZDUSD",
    name: "New Zealand Dollar vs US Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "CHFJPY",
    name: "Swiss Franc vs Japanese Yen",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "JPY",
  },
  {
    symbol: "USDCAD",
    name: "US Dollar vs Canadian Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CAD",
  },
  {
    symbol: "USDCHF",
    name: "US Dollar vs Swiss Franc",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "CHF",
  },
  {
    symbol: "USDJPY",
    name: "US Dollar vs Japanese Yen",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "JPY",
  },
  {
    symbol: "EURCZK",
    name: "Euro vs Czech Republic Koruna",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.0001",
    profitCurrency: "CZK",
  },
  {
    symbol: "EURHUF",
    name: "Euro vs Hungarian Forint",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "HUF",
  },
  {
    symbol: "EURNOK",
    name: "Euro vs Norwegian Krone",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "NOK",
  },
  {
    symbol: "EURPLN",
    name: "Euro vs Polish Zloty",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "PLN",
  },
  {
    symbol: "USDCZK",
    name: "US Dollar vs Czech Republic Koruna",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.0001",
    profitCurrency: "CZK",
  },
  {
    symbol: "USDHKD",
    name: "US Dollar vs Hong Kong Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "HKD",
  },
  {
    symbol: "USDHUF",
    name: "US Dollar vs Hungarian Forint",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.001",
    profitCurrency: "HUF",
  },
  {
    symbol: "USDILS",
    name: "US Dollar vs Israeli New Sheqel",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "ILS",
  },
  {
    symbol: "USDMXN",
    name: "US Dollar vs Mexican Peso",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "MXN",
  },
  {
    symbol: "USDNOK",
    name: "US Dollar vs Norwegian Krone",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "NOK",
  },
  {
    symbol: "USDPLN",
    name: "US Dollar vs Polish Zloty",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "PLN",
  },
  {
    symbol: "USDSGD",
    name: "US Dollar vs Singapore Dollar",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "SGD",
  },
  {
    symbol: "USDZAR",
    name: "US Dollar vs South African Rand",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "ZAR",
  },
  {
    symbol: "USDSEK",
    name: "US Dollar vs Swedish Krona",
    assetClass: "forex",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "SEK",
  },
  {
    symbol: "XAGUSD",
    name: "Silver vs US Dollar, Spot CFD",
    assetClass: "metal",
    pointValue: "5000",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "XAGEUR",
    name: "Silver vs Euro, Spot CFD",
    assetClass: "metal",
    pointValue: "5000",
    tickSize: "0.001",
    profitCurrency: "EUR",
  },
  {
    symbol: "XAGAUD",
    name: "Silver vs Australian Dollar, Spot CFD",
    assetClass: "metal",
    pointValue: "5000",
    tickSize: "0.001",
    profitCurrency: "AUD",
  },
  {
    symbol: "XAUUSD",
    name: "Gold vs US Dollar, Spot CFD",
    assetClass: "metal",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "XAUEUR",
    name: "Gold vs Euro, Spot CFD",
    assetClass: "metal",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "EUR",
  },
  {
    symbol: "XAUAUD",
    name: "Gold vs Australian Dollar, Spot CFD",
    assetClass: "metal",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "AUD",
  },
  {
    symbol: "XPDUSD",
    name: "Palladium vs United States Dollar, Spot CFD",
    assetClass: "metal",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "XPTUSD",
    name: "Platinum vs United States Dollar, Spot CFD",
    assetClass: "metal",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "XCUUSD",
    name: "Copper vs US Dollar, Spot CFD",
    assetClass: "metal",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "UKOIL.cash",
    name: "Crude Oil Brent, Spot CFD",
    assetClass: "commodity",
    pointValue: "100",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "USOIL.cash",
    name: "West Texas Intermediate Crude Oil, Spot CFD",
    assetClass: "commodity",
    pointValue: "100",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "NATGAS.cash",
    name: "Natural Gas Instrument, Spot CFD",
    assetClass: "commodity",
    pointValue: "1000",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "COCOA.c",
    name: "Cocoa vs US Dollar, Spot CFD",
    assetClass: "commodity",
    pointValue: "1",
    tickSize: "0.1",
    profitCurrency: "USD",
  },
  {
    symbol: "COFFEE.c",
    name: "Coffee vs US Dollar, Spot CFD",
    assetClass: "commodity",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "CORN.c",
    name: "Corn vs US Dollar, Spot CFD",
    assetClass: "commodity",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "SOYBEAN.c",
    name: "Soybean vs US Dollar, Spot CFD",
    assetClass: "commodity",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "WHEAT.c",
    name: "Wheat, Spot CFD",
    assetClass: "commodity",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "HEATOIL.c",
    name: "Heating Oil, Spot CFD",
    assetClass: "commodity",
    pointValue: "100",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "COTTON.c",
    name: "Cotton vs US Dollar, Spot CFD",
    assetClass: "commodity",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "SUGAR.c",
    name: "Sugar vs US Dollar, Spot CFD",
    assetClass: "commodity",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "BTCUSD",
    name: "Bitcoin vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "DASHUSD",
    name: "Dash vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1000",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "ETHUSD",
    name: "Ethereum vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "10",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "LTCUSD",
    name: "Litecoin vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "XRPUSD",
    name: "Ripple vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "10000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "XMRUSD",
    name: "Monero vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "NEOUSD",
    name: "Neo vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1000",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "ADAUSD",
    name: "Cardano vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.0001",
    profitCurrency: "USD",
  },
  {
    symbol: "DOTUSD",
    name: "Polkadot vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "10000",
    tickSize: "0.0001",
    profitCurrency: "USD",
  },
  {
    symbol: "DOGEUSD",
    name: "Dogecoin vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "SOLUSD",
    name: "Solana vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "AVAUSD",
    name: "Avalanche vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1000",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "BCHUSD",
    name: "BitCoin Cash vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "ETCUSD",
    name: "Ethereum Classic vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1000",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "BNBUSD",
    name: "Binance Coin vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "SANUSD",
    name: "The Sandbox vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.0001",
    profitCurrency: "USD",
  },
  {
    symbol: "LNKUSD",
    name: "Chainlink vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1000",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "NERUSD",
    name: "NEAR protocol vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "10000",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "ALGUSD",
    name: "Algorand vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.0001",
    profitCurrency: "USD",
  },
  {
    symbol: "ICPUSD",
    name: "Internet Computer vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "10000",
    tickSize: "0.001",
    profitCurrency: "USD",
  },
  {
    symbol: "AAVUSD",
    name: "AAVE vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100",
    tickSize: "0.01",
    profitCurrency: "USD",
  },
  {
    symbol: "BARUSD",
    name: "Hedera vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "GALUSD",
    name: "GALA vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1000000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "GRTUSD",
    name: "The Graph vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1000000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "IMXUSD",
    name: "Immutable X vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.0001",
    profitCurrency: "USD",
  },
  {
    symbol: "MANUSD",
    name: "Decentraland vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "VECUSD",
    name: "VeChain vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "1000000",
    tickSize: "0.00001",
    profitCurrency: "USD",
  },
  {
    symbol: "XLMUSD",
    name: "Stellar Lumens vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.0001",
    profitCurrency: "USD",
  },
  {
    symbol: "UNIUSD",
    name: "Uniswap vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "10000",
    tickSize: "0.0001",
    profitCurrency: "USD",
  },
  {
    symbol: "XTZUSD",
    name: "Tezos vs US Dollar, Spot CFD",
    assetClass: "crypto",
    pointValue: "100000",
    tickSize: "0.0001",
    profitCurrency: "USD",
  },
];

const INSTRUMENTS = [...FUTURES, ...CFDS];

async function seed() {
  for (const instrument of INSTRUMENTS) {
    await db
      .insert(instruments)
      .values(instrument)
      .onConflictDoUpdate({
        target: instruments.symbol,
        set: {
          name: instrument.name,
          assetClass: instrument.assetClass,
          pointValue: instrument.pointValue,
          tickSize: instrument.tickSize,
          profitCurrency: instrument.profitCurrency,
        },
      });
  }

  console.log(`Seeded ${INSTRUMENTS.length} instruments.`);
  process.exit(0);
}

seed().catch((error) => {
  console.error(error);
  process.exit(1);
});
